import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { fileURLToPath, URL } from 'node:url'
import { defineConfig, loadEnv, lazyPlugins } from 'vite-plus'

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')

  return {
    fmt: {
      semi: false,
      singleQuote: true,
    },
    lint: {
      plugins: ['typescript', 'react'],
      categories: {
        correctness: 'off',
      },
      options: {
        typeAware: true,
        typeCheck: true,
      },
      env: {
        builtin: true,
      },
      ignorePatterns: ['dist', 'node_modules', 'test-results'],
      rules: {
        'constructor-super': 'error',
        'for-direction': 'error',
        'getter-return': 'error',
        'no-async-promise-executor': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-const-assign': 'error',
        'no-constant-binary-expression': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-pattern': 'error',
        'no-empty-static-block': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-fallthrough': 'error',
        'no-func-assign': 'error',
        'no-global-assign': 'error',
        'no-import-assign': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-nonoctal-decimal-escape': 'error',
        'no-obj-calls': 'error',
        'no-prototype-builtins': 'error',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-self-assign': 'error',
        'no-setter-return': 'error',
        'no-shadow-restricted-names': 'error',
        'no-sparse-arrays': 'error',
        'no-this-before-super': 'error',
        'no-unassigned-vars': 'error',
        'no-undef': 'error',
        'no-unexpected-multiline': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-labels': 'error',
        'no-unused-private-class-members': 'error',
        'no-unused-vars': 'error',
        'no-useless-assignment': 'error',
        'no-useless-backreference': 'error',
        'no-useless-catch': 'error',
        'no-useless-escape': 'error',
        'no-with': 'error',
        'preserve-caught-error': 'error',
        'require-yield': 'error',
        'use-isnan': 'error',
        'valid-typeof': 'error',
        'no-array-constructor': 'error',
        'no-unused-expressions': 'error',
        'typescript/await-thenable': 'error',
        'typescript/ban-ts-comment': 'error',
        'typescript/no-array-delete': 'error',
        'typescript/no-base-to-string': 'error',
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'error',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-floating-promises': 'error',
        'typescript/no-for-in-array': 'error',
        'typescript/no-implied-eval': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-misused-promises': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-redundant-type-constituents': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': 'error',
        'typescript/restrict-template-expressions': 'error',
        'typescript/triple-slash-reference': 'error',
        'typescript/unbound-method': 'error',
        'vite-plus/prefer-vite-plus-imports': 'error',
        'shadcn/no-raw-colors': [
          'error',
          {
            message: 'Use Prelude semantic tokens from frontend/src/shared/styles/index.css.',
          },
        ],
        'shadcn/no-arbitrary-values': [
          'error',
          {
            message:
              'Use theme scale values from DESIGN.md (spacing, radius, size). Do not invent pixel/arbitrary utilities.',
          },
        ],
        'shadcn/no-inline-styles': [
          'error',
          {
            allow: ['--report-score-fill'],
            message:
              'Style tokens and layout belong in CSS (shared/styles or feature CSS). Inline styles only for documented runtime CSS variables.',
          },
        ],
        'shadcn/require-static-classes': [
          'error',
          {
            message:
              'Class names must be static literals so architecture and design gates can read them.',
          },
        ],
        'shadcn/no-restyle': [
          'warn',
          {
            // BEM page classes (e.g. login-card__submit) collide with Tailwind restyle detection.
            // DS components still get contracts below so appearance/spacing overrides fail loudly.
            allow: ['layout'],
            contracts: [
              {
                pattern: '^Button$',
                allow: ['layout'],
                deny: ['spacing', 'color', 'typography', 'shape', 'effects'],
                message:
                  'Button owns spacing, color, type, and shape via variant/size. Place with layout classes or parent gap; do not restyle.',
              },
              {
                pattern: '^Input$|^Textarea$',
                allow: ['layout'],
                deny: ['color', 'typography', 'shape', 'effects'],
                message:
                  'Fields own surface, border, and type (DESIGN.md Fields). Use error/hint props; layout only via parent.',
              },
              {
                pattern: '^Select$',
                allow: ['layout'],
                deny: ['color', 'typography', 'shape', 'effects'],
                message: 'Select owns its control chrome. Keep surface/border from shared tokens.',
              },
              {
                pattern: '^DropdownMenu(Item|RadioItem|CheckboxItem)$',
                allow: ['layout'],
                deny: ['color', 'typography', 'shape', 'effects'],
                message:
                  'Menu items use the shared floating-surface chrome. Do not restyle item appearance.',
              },
              {
                pattern: '^IconTooltip$|^Modal$',
                allow: ['layout'],
                deny: ['color', 'typography', 'shape', 'effects'],
                message:
                  'Floating surfaces keep the shared high-contrast neutral chrome from DESIGN.md.',
              },
              {
                pattern: '^SegmentedControl$',
                allow: ['layout'],
                deny: ['spacing', 'color', 'typography', 'shape'],
                message:
                  'SegmentedControl owns its tracks and labels. Change items via props, not className restyle.',
              },
            ],
          },
        ],
        'shadcn/no-unknown-classes': 'warn',
      },
      settings: {
        shadcn: {
          ui: '@/shared/ui',
          componentImports: ['^@/shared/ui'],
          mergeFunctions: ['cn'],
          note: 'See DESIGN.md and frontend/src/shared/styles/index.css. Prelude semantic tokens only.',
        },
      },
      overrides: [
        {
          files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
          rules: {
            'constructor-super': 'off',
            'getter-return': 'off',
            'no-class-assign': 'off',
            'no-const-assign': 'off',
            'no-dupe-class-members': 'off',
            'no-dupe-keys': 'off',
            'no-func-assign': 'off',
            'no-import-assign': 'off',
            'no-new-native-nonconstructor': 'off',
            'no-obj-calls': 'off',
            'no-redeclare': 'off',
            'no-setter-return': 'off',
            'no-this-before-super': 'off',
            'no-undef': 'off',
            'no-unreachable': 'off',
            'no-unsafe-negation': 'off',
            'no-var': 'error',
            'no-with': 'off',
            'prefer-const': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
          },
        },
        {
          files: ['**/*.{ts,tsx}'],
          rules: {
            'react/rules-of-hooks': 'error',
            'react/exhaustive-deps': 'error',
            'react/static-components': 'error',
            'react/use-memo': 'error',
            'react/preserve-manual-memoization': 'error',
            'react/incompatible-library': 'error',
            'react/immutability': 'error',
            'react/globals': 'error',
            'react/refs': 'error',
            'react/set-state-in-effect': 'error',
            'react/error-boundaries': 'error',
            'react/purity': 'error',
            'react/set-state-in-render': 'error',
            'react/unsupported-syntax': 'error',
            'react/only-export-components': [
              'error',
              {
                allowConstantExport: true,
                allowExportNames: ['useFeedback', 'printInterviewReport'],
              },
            ],
          },
          env: {
            es2026: true,
            browser: true,
          },
        },
        {
          files: ['vite.config.ts', 'playwright.config.ts', 'tests/**/*.ts'],
          env: {
            node: true,
          },
        },
        {
          files: ['**/*.{js,mjs,cjs}'],
          rules: {
            'typescript/await-thenable': 'off',
            'typescript/consistent-return': 'off',
            'typescript/consistent-type-exports': 'off',
            'typescript/dot-notation': 'off',
            'typescript/no-array-delete': 'off',
            'typescript/no-base-to-string': 'off',
            'typescript/no-confusing-void-expression': 'off',
            'typescript/no-deprecated': 'off',
            'typescript/no-duplicate-type-constituents': 'off',
            'typescript/no-floating-promises': 'off',
            'typescript/no-for-in-array': 'off',
            'typescript/no-implied-eval': 'off',
            'typescript/no-meaningless-void-operator': 'off',
            'typescript/no-misused-promises': 'off',
            'typescript/no-misused-spread': 'off',
            'typescript/no-mixed-enums': 'off',
            'typescript/no-redundant-type-constituents': 'off',
            'typescript/no-unnecessary-boolean-literal-compare': 'off',
            'typescript/no-unnecessary-condition': 'off',
            'typescript/no-unnecessary-qualifier': 'off',
            'typescript/no-unnecessary-template-expression': 'off',
            'typescript/no-unnecessary-type-arguments': 'off',
            'typescript/no-unnecessary-type-assertion': 'off',
            'typescript/no-unnecessary-type-conversion': 'off',
            'typescript/no-unnecessary-type-parameters': 'off',
            'typescript/no-unsafe-argument': 'off',
            'typescript/no-unsafe-assignment': 'off',
            'typescript/no-unsafe-call': 'off',
            'typescript/no-unsafe-enum-comparison': 'off',
            'typescript/no-unsafe-member-access': 'off',
            'typescript/no-unsafe-return': 'off',
            'typescript/no-unsafe-type-assertion': 'off',
            'typescript/no-unsafe-unary-minus': 'off',
            'typescript/no-useless-default-assignment': 'off',
            'typescript/non-nullable-type-assertion-style': 'off',
            'typescript/only-throw-error': 'off',
            'typescript/prefer-find': 'off',
            'typescript/prefer-includes': 'off',
            'typescript/prefer-nullish-coalescing': 'off',
            'typescript/prefer-optional-chain': 'off',
            'typescript/prefer-promise-reject-errors': 'off',
            'typescript/prefer-readonly': 'off',
            'typescript/prefer-readonly-parameter-types': 'off',
            'typescript/prefer-reduce-type-parameter': 'off',
            'typescript/prefer-regexp-exec': 'off',
            'typescript/prefer-return-this-type': 'off',
            'typescript/prefer-string-starts-ends-with': 'off',
            'typescript/promise-function-async': 'off',
            'typescript/related-getter-setter-pairs': 'off',
            'typescript/require-array-sort-compare': 'off',
            'typescript/require-await': 'off',
            'typescript/restrict-plus-operands': 'off',
            'typescript/restrict-template-expressions': 'off',
            'typescript/return-await': 'off',
            'typescript/strict-boolean-expressions': 'off',
            'typescript/strict-void-return': 'off',
            'typescript/switch-exhaustiveness-check': 'off',
            'typescript/unbound-method': 'off',
            'typescript/use-unknown-in-catch-callback-variable': 'off',
            'typescript/no-require-imports': 'off',
          },
          env: {
            node: true,
          },
        },
        {
          // Component implementation owns its primitive styles; restyle/arbitrary/static-class
          // gates apply at call sites. Token and inline-style rules still apply here.
          files: ['src/shared/ui/**'],
          rules: {
            'shadcn/no-restyle': 'off',
            'shadcn/no-arbitrary-values': 'off',
            'shadcn/require-static-classes': 'off',
          },
        },
      ],
      jsPlugins: [
        {
          name: 'vite-plus',
          specifier: 'vite-plus/oxlint-plugin',
        },
        {
          name: 'shadcn',
          specifier: '@shadcn/lint',
        },
      ],
    },
    plugins: lazyPlugins(() => [react(), tailwindcss()]),
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
    server: {
      host: env.VITE_HOST || '127.0.0.1',
      port: Number(env.VITE_PORT || 5173),
      proxy: {
        '/api': {
          target: env.VITE_PROXY_TARGET || 'http://127.0.0.1:8080',
          changeOrigin: true,
          ws: true,
          configure(proxy) {
            proxy.on('proxyReq', (proxyRequest) => proxyRequest.removeHeader('origin'))
          },
        },
      },
    },
  }
})
